
[platformio]
src_dir = firmware/src
include_dir = firmware/inc
default_envs = node1

[env]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
build_flags = 
    -Ifirmware/inc
    -Ifirmware/lib/crypto
    -Ifirmware/lib/kuznyechik
    -DSTM32F103xB
    -DUSE_USB_CDC
    -DUSBD_USE_CDC
lib_extra_dirs = 
    firmware/lib

[env:node1]
build_flags = 
    ${env.build_flags}
    -DNODE_ID=1

[env:node2]
build_flags = 
    ${env.build_flags}
    -DNODE_ID=2
    -DWORK_AS_LOOPBACK_FOR_NODE_2
